version: "3"

services:
  postgres:
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    container_name: db
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  db-data:
