"""RestaurantTable

Revision ID: 64d727ca3883
Revises: 7d300ceb3d6e
Create Date: 2021-12-23 01:05:42.610276

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '64d727ca3883'
down_revision = '7d300ceb3d6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant_table',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id', 'restaurant_id')
    )
    op.create_foreign_key(None, 'order', 'restaurant_table', ['table_index'], ['index'])
    op.drop_column('restaurant', 'tables')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurant', sa.Column('tables', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_table('restaurant_table')
    # ### end Alembic commands ###
