"""Restaurant, MenuItem, Order tables

Revision ID: 7d300ceb3d6e
Revises: 
Create Date: 2021-12-23 00:34:20.929267

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7d300ceb3d6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tables', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_item',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('price_value', sa.DECIMAL(), nullable=False),
    sa.Column('restaurant_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('table_index', sa.Integer(), nullable=False),
    sa.Column('total_price_value', sa.DECIMAL(), nullable=False),
    sa.Column('restaurant_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_and_menu_item_association_table',
    sa.Column('order_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('menu_item_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_item.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'menu_item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_and_menu_item_association_table')
    op.drop_table('order')
    op.drop_table('menu_item')
    op.drop_table('restaurant')
    # ### end Alembic commands ###
